# Generated by Django 4.0.3 on 2024-02-01 12:00

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('methods', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_type', models.CharField(max_length=120, unique=True)),
                ('time_deleted', models.DateTimeField(blank=True, null=True)),
            ],
            managers=[
                ('objects_service', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Service_method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_deleted', models.DateTimeField(blank=True, null=True)),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='method_set', to='methods.method')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_set', to='services.service')),
                ('service_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_device_set', to='service_method.service_device')),
            ],
            managers=[
                ('objects_service', django.db.models.manager.Manager()),
            ],
        ),
    ]
