# Generated by Django 4.0.3 on 2024-04-03 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_method', '0002_alter_service_device_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='service_device',
            table='serviceCompany_Device',
        ),
        migrations.AlterModelTable(
            name='service_method',
            table='serviceCompany_ConnectMethod',
        ),
    ]
