# Generated by Django 4.0.3 on 2024-02-01 12:00

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Method_parametrs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('abbreviation', models.CharField(max_length=120)),
                ('curve_type', models.CharField(max_length=120)),
                ('units', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=120), blank=True, default=list, size=None)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Mnemonic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('method_parametr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='method_mnem_set', to='method_parametrs.method_parametrs')),
            ],
        ),
    ]
