# Generated by Django 4.0.3 on 2024-02-01 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('methods', '0001_initial'),
        ('method_parametrs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='method_parametrs',
            name='method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='method_params_set', to='methods.method'),
        ),
    ]
