# Generated by Django 4.0.3 on 2024-04-03 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('methods', '0002_alter_method_method_class_alter_method_table'),
        ('method_parametrs', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='method_parametrs',
            name='method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='method_parametrs_set', to='methods.method'),
        ),
        migrations.AlterModelTable(
            name='method_parametrs',
            table='method_parametrs',
        ),
        migrations.AlterModelTable(
            name='mnemonic',
            table='method_mnemonic',
        ),
    ]
