# Generated by Django 4.0.3 on 2024-02-01 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('fields', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('strata_file', models.FileField(blank=True, default='', null=True, upload_to='api/strata/%Y/%m/%d/')),
                ('time_deleted', models.DateTimeField(blank=True, null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_strata_set', to='fields.field')),
            ],
            options={
                'verbose_name': 'Strata',
                'ordering': ['name'],
            },
        ),
    ]
