# Generated by Django 4.0.3 on 2024-04-03 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('method_class', '0002_alter_method_class_table'),
        ('methods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='method',
            name='method_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='method_set', to='method_class.method_class'),
        ),
        migrations.AlterModelTable(
            name='method',
            table='method',
        ),
    ]
