# Generated by Django 4.0.3 on 2024-02-01 12:00

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quality_control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inform_for_method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_num', models.CharField(max_length=120)),
                ('calibr_date', models.DateField(blank=True, null=True)),
                ('interval_shod_start', models.FloatField(blank=True, null=True)),
                ('interval_shod_end', models.FloatField(blank=True, null=True)),
                ('reason_rashod', models.CharField(blank=True, choices=[('Низкая плотность данных реального времени', 'Low Realtime Data Density'), ('Проблема с передачей данных реального времени', 'Realtime Data Transmission'), ('Перерасчет данных из памяти прибора', 'Recalculation Data From Device Memory'), ('', 'None Value')], max_length=120)),
                ('petrophysic_task', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('petrophysic_selected', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=120), blank=True, default=list, size=None)),
                ('method_value', models.FloatField(blank=True, null=True)),
                ('time_deleted', models.DateTimeField(blank=True, null=True)),
                ('quality_control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_control_set', to='quality_control.quality_control')),
            ],
        ),
        migrations.CreateModel(
            name='Koef_fail',
            fields=[
                ('koef_fail', models.FloatField(blank=True, null=True)),
                ('inform_for_method', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='inform_for_koef_fail_set', serialize=False, to='inform_for_method.inform_for_method')),
            ],
        ),
        migrations.CreateModel(
            name='Koef_shod',
            fields=[
                ('koef_shod', models.FloatField(blank=True, null=True)),
                ('inform_for_method', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='inform_for_koef_shod_set', serialize=False, to='inform_for_method.inform_for_method')),
            ],
        ),
    ]
