# Generated by Django 4.0.3 on 2024-02-01 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inform_for_method', '0001_initial'),
        ('service_method', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inform_for_method',
            name='service_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_method_set', to='service_method.service_method'),
        ),
        migrations.AddConstraint(
            model_name='inform_for_method',
            constraint=models.CheckConstraint(check=models.Q(('petrophysic_task__gte', 0.0), ('petrophysic_task__lte', 1.0)), name='inform_for_method_petrophysic_task_range'),
        ),
    ]
