# Generated by Django 4.0.3 on 2024-04-01 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inform_for_method', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='inform_for_method',
            table='quality_Method1',
        ),
    ]
