# Generated by Django 4.0.3 on 2024-04-01 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_method', '0001_initial'),
        ('inform_for_method', '0003_alter_inform_for_method_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inform_for_method',
            name='service_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inform_for_method_set', to='service_method.service_method'),
        ),
    ]
