# Generated by Django 4.0.3 on 2024-02-01 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wells', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wellbore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ILWD_LU', models.CharField(blank=True, choices=[('Выполнена', 'Done'), ('Не выполнена', 'Not'), ('', 'None Value')], max_length=120)),
                ('WP_DM', models.CharField(blank=True, choices=[('Да', 'Yes'), ('Нет', 'No'), ('', 'None Value')], max_length=120)),
                ('WP_GRemark', models.TextField(blank=True, null=True)),
                ('ILWD_TI', models.CharField(blank=True, max_length=120, null=True)),
                ('ILWD_TFS', models.CharField(blank=True, max_length=120, null=True)),
                ('ILWD_TLS', models.CharField(blank=True, max_length=120, null=True)),
                ('ILWD_TRS', models.CharField(blank=True, max_length=120, null=True)),
                ('ILWD_TM', models.CharField(blank=True, max_length=120, null=True)),
                ('ILQC_TR', models.CharField(blank=True, max_length=120, null=True)),
                ('ILWD_A', models.CharField(blank=True, max_length=120, null=True)),
                ('ILQC_A', models.CharField(blank=True, max_length=120, null=True)),
                ('ILQC_C', models.CharField(blank=True, max_length=120, null=True)),
                ('main_strata', models.CharField(blank=True, max_length=120, null=True)),
                ('contractor', models.CharField(blank=True, max_length=120, null=True)),
                ('WP_DL', models.FloatField(blank=True, null=True)),
                ('WP_TD', models.FloatField(blank=True, null=True)),
                ('ILWD_I', models.CharField(blank=True, choices=[('Круглосуточная', 'Noctidial'), ('На финальный забой', 'Forfinal'), ('', 'None Value')], max_length=120)),
                ('status_wellbore', models.CharField(blank=True, choices=[('Должна начаться', 'Start'), ('В бурении', 'Drilling'), ('В ожидании', 'Pending'), ('Добурена', 'Finished'), ('Отчет отправлен', 'Reportsent'), ('', 'None Value')], max_length=120)),
                ('WP_PCS', models.FloatField(blank=True, null=True)),
                ('WP_PT1', models.FloatField(blank=True, null=True)),
                ('WP_PT3', models.FloatField(blank=True, null=True)),
                ('WP_PWL', models.FloatField(blank=True, null=True)),
                ('WP_PCP', models.FloatField(blank=True, null=True)),
                ('WP_CS', models.FloatField(blank=True, null=True)),
                ('WP_T1', models.FloatField(blank=True, null=True)),
                ('WP_T3', models.FloatField(blank=True, null=True)),
                ('WP_WL', models.FloatField(blank=True, null=True)),
                ('WP_CP', models.FloatField(blank=True, null=True)),
                ('num_wellbore', models.CharField(max_length=120)),
                ('pie_well', models.CharField(blank=True, choices=[('Горизонтальный', 'Horizontal'), ('Транспортный', 'Transport'), ('Пилотный', 'Pilot'), ('Боковой', 'Lateral'), ('', 'None Value')], max_length=120)),
                ('diametr', models.FloatField(blank=True, null=True)),
                ('time_deleted', models.DateTimeField(blank=True, null=True)),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='well_set', to='wells.well')),
            ],
            options={
                'verbose_name': 'Wellbore',
                'verbose_name_plural': 'Wellbores',
                'ordering': ['pie_well'],
            },
        ),
    ]
