# Generated by Django 4.0.3 on 2024-02-01 11:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wellbores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_file', models.FileField(upload_to='sample/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Quality_control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=120, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('density', models.FloatField(blank=True, null=True)),
                ('section_interval_start', models.FloatField(blank=True, null=True)),
                ('section_interval_end', models.FloatField(blank=True, null=True)),
                ('data_of_created', models.DateField(auto_now_add=True)),
                ('date_of_changed', models.DateField(default=datetime.date.today)),
                ('data_type', models.CharField(choices=[('Из памяти прибора', 'From Device Memory'), ('Реального времени', 'Real Time'), ('', 'None Value')], max_length=120)),
                ('note', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('time_deleted', models.DateTimeField(blank=True, null=True)),
                ('wellbore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wellbore_set', to='wellbores.wellbore')),
            ],
            options={
                'verbose_name': 'Quality',
                'verbose_name_plural': 'Qualities',
                'ordering': ['value'],
            },
        ),
    ]
