# Generated by Django 4.0.3 on 2024-03-04 09:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wellbores', '0001_initial'),
        ('quality_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quality_control',
            options={'ordering': ['value'], 'verbose_name': 'Отчёт', 'verbose_name_plural': 'Отчёты'},
        ),
        migrations.AddField(
            model_name='quality_control',
            name='accompaniment_type',
            field=models.CharField(blank=True, choices=[('Т3', 'Т3'), ('Круглосуточное', 'Круглосуточное')], max_length=120, null=True, verbose_name='Тип сопровождения'),
        ),
        migrations.AlterField(
            model_name='quality_control',
            name='author',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='quality_control',
            name='data_of_created',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='quality_control',
            name='data_type',
            field=models.CharField(choices=[('Из памяти прибора', 'From Device Memory'), ('Реального времени', 'Real Time'), ('', 'None Value')], max_length=120, verbose_name='Вид данных'),
        ),
        migrations.AlterField(
            model_name='quality_control',
            name='date_of_changed',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата редактирования'),
        ),
        migrations.AlterField(
            model_name='quality_control',
            name='density',
            field=models.FloatField(blank=True, null=True, verbose_name='Плотность данных'),
        ),
        migrations.AlterField(
            model_name='quality_control',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата ГИС конец'),
        ),
        migrations.AlterField(
            model_name='quality_control',
            name='section_interval_end',
            field=models.FloatField(blank=True, null=True, verbose_name='Интервал секции(конец)'),
        ),
        migrations.AlterField(
            model_name='quality_control',
            name='section_interval_start',
            field=models.FloatField(blank=True, null=True, verbose_name='Интервал секции(начало)'),
        ),
        migrations.AlterField(
            model_name='quality_control',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата ГИС начало'),
        ),
        migrations.AlterField(
            model_name='quality_control',
            name='value',
            field=models.FloatField(blank=True, null=True, verbose_name='Общая оценка'),
        ),
        migrations.AlterField(
            model_name='quality_control',
            name='wellbore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wellbore_set', to='wellbores.wellbore', verbose_name='Скважина'),
        ),
    ]
