# Generated by Django 4.0.3 on 2024-03-19 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        ('quality_control', '0002_alter_quality_control_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quality_control',
            name='service_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.service', verbose_name='Сервисная компания'),
        ),
    ]
