# Generated by Django 4.0.3 on 2024-03-25 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quality_control', '0003_quality_control_service_company'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='quality_control',
            table='quality_Report',
        ),
    ]
