# Generated by Django 4.0.3 on 2024-03-27 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quality_control', '0004_alter_quality_control_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sample',
            options={'verbose_name': 'Шаблоны', 'verbose_name_plural': 'Шаблон'},
        ),
        migrations.AlterModelTable(
            name='sample',
            table='quality_Sample',
        ),
    ]
