# Generated by Django 4.0.3 on 2024-04-01 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_control', '0005_alter_sample_options_alter_sample_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sample',
            options={'verbose_name': 'Шаблон', 'verbose_name_plural': 'Шаблоны'},
        ),
        migrations.AddField(
            model_name='quality_control',
            name='complex_definition',
            field=models.CharField(blank=True, choices=[('ГК+УЭС', 'ГК+УЭС'), ('Полный', 'Полный'), ('Специальный', 'Специальный'), ('None', '')], max_length=120, null=True, verbose_name='Автоматическое определение комплекса'),
        ),
    ]
