# Generated by Django 4.0.3 on 2024-04-03 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('method_class', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='method_class',
            table='method_class',
        ),
    ]
