# Generated by Django 4.0.3 on 2024-02-01 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quality_control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Full_inform',
            fields=[
                ('quality_control', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='full_inform_set', serialize=False, to='quality_control.quality_control')),
                ('act', models.CharField(blank=True, choices=[('Имеется', 'True'), ('Не имеется', 'False'), ('', 'None Value')], max_length=120)),
                ('titul_list', models.CharField(blank=True, choices=[('Полная', 'Full'), ('Частичная', 'Partial'), ('Отсутствует', 'Absent'), ('', 'None Value')], max_length=120)),
                ('well_construction', models.CharField(blank=True, choices=[('Имеется', 'True'), ('Не имеется', 'False'), ('', 'None Value')], max_length=120)),
                ('wellbore_sizes', models.CharField(blank=True, choices=[('Полная', 'Full'), ('Частичная', 'Partial'), ('Отсутствует', 'Absent'), ('', 'None Value')], max_length=120)),
                ('chrono_data', models.CharField(blank=True, choices=[('Имеется', 'True'), ('Не имеется', 'False'), ('', 'None Value')], max_length=120)),
                ('sol_data', models.CharField(blank=True, choices=[('Полная', 'Full'), ('Частичная', 'Partial'), ('Отсутствует', 'Absent'), ('', 'None Value')], max_length=120)),
                ('dash_comp', models.CharField(blank=True, choices=[('Полная', 'Full'), ('Частичная', 'Partial'), ('Отсутствует', 'Absent'), ('', 'None Value')], max_length=120)),
                ('summary_data', models.CharField(blank=True, choices=[('Имеется', 'True'), ('Не имеется', 'False'), ('', 'None Value')], max_length=120)),
                ('inklino_data', models.CharField(blank=True, choices=[('Имеется', 'True'), ('Не имеется', 'False'), ('', 'None Value')], max_length=120)),
                ('main_record', models.CharField(blank=True, choices=[('Полная', 'Full'), ('Частичная', 'Partial'), ('Отсутствует', 'Absent'), ('', 'None Value')], max_length=120)),
                ('parametr', models.CharField(blank=True, choices=[('Имеется', 'True'), ('Не имеется', 'False'), ('', 'None Value')], max_length=120)),
                ('control_record', models.CharField(blank=True, choices=[('Имеется', 'True'), ('Не имеется', 'False'), ('', 'None Value')], max_length=120)),
                ('lqc', models.CharField(blank=True, choices=[('Имеется', 'True'), ('Не имеется', 'False'), ('', 'None Value')], max_length=120)),
                ('calibration', models.CharField(blank=True, choices=[('Полная', 'Full'), ('Частичная', 'Partial'), ('Отсутствует', 'Absent'), ('', 'None Value')], max_length=120)),
                ('full_inf_count', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
