# Generated by Django 4.0.3 on 2024-03-25 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('full_inform', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='full_inform',
            options={'verbose_name': 'Полнота представления данных', 'verbose_name_plural': 'Полнота представления данных'},
        ),
    ]
