# Generated by Django 4.0.3 on 2024-02-01 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inform_for_method', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Second_table',
            fields=[
                ('inform_for_method', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='inform_for_method_set', serialize=False, to='inform_for_method.inform_for_method')),
                ('linkage', models.CharField(blank=True, choices=[('Увязан', 'Related'), ('Частично неувязан', 'Partially Unrelated'), ('Неувязан', 'Unrelated'), ('', 'None Value')], max_length=120)),
                ('emissions', models.CharField(blank=True, choices=[('Отсутствуют', 'Absent'), ('Единичные', 'Single'), ('Регулярные', 'Regular'), ('', 'None Value')], max_length=120)),
                ('noise', models.CharField(blank=True, choices=[('Отсутствует', 'Absent'), ('Незначительная', 'Insignificant'), ('Высокая', 'High'), ('', 'None Value')], max_length=120)),
                ('control', models.CharField(blank=True, choices=[('Соответствует основному замеру', 'To Basic Measurement'), ('Отменена по согласованию сторон', 'Canceled'), ('Не соответствует основной записи', 'Does Not Match'), ('Не произведена', 'Not Produced'), ('', 'None Value')], max_length=120)),
                ('distribute_support', models.CharField(blank=True, choices=[('Соответствует данным опорных скважин', 'Corresponds'), ('Не соответствует данным опорных скважин (занижено)', 'Underestimated'), ('Не соответствует данным опорных скважин (завышено)', 'Overestimated'), ('', 'None Value')], max_length=120)),
                ('distribute_palet', models.CharField(blank=True, choices=[('Лежат в области ожидаемых значений', 'Are In'), ('Не лежат в области ожидаемых значений', 'Are Not In'), ('', 'None Value')], max_length=120)),
                ('dash', models.CharField(blank=True, choices=[('Соответствуют', 'Match'), ('Не соответствуют', 'Not Match'), ('', 'None Value')], max_length=120)),
                ('corresponse', models.CharField(blank=True, choices=[('Соответствуют', 'Match'), ('Занижены', 'Underestimated'), ('Завышены', 'Оverestimated'), ('Реперные горизонты не вскрыты', 'Not Revealed'), ('Свойства реперного горизонта отсутствуют', 'No Reference Horizon Properties'), ('Свойства реперного горизонта расходятся', 'Diverge'), ('', 'None Value')], max_length=120)),
                ('correlation', models.CharField(blank=True, choices=[('Коррелируют', 'Good'), ('Частично коррелируют', 'Satisfactory'), ('Не коррелируют', 'Unsatisfactory'), ('', 'None Value')], max_length=120)),
                ('device_tech_condition', models.CharField(blank=True, choices=[('Хорошее', 'Good'), ('Удовлетворительное', 'Satisfactory'), ('Неудовлетворительное', 'Unsatisfactory'), ('', 'None Value')], max_length=120)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
