# Generated by Django 4.0.3 on 2024-04-01 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second_table', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='second_table',
            table='quality_Method2',
        ),
    ]
