# Generated by Django 4.0.3 on 2024-04-01 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inform_for_method', '0004_alter_inform_for_method_service_method'),
        ('second_table', '0002_alter_second_table_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='second_table',
            name='inform_for_method',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='second_table_set', serialize=False, to='inform_for_method.inform_for_method'),
        ),
    ]
