# Generated by Django 4.0.3 on 2024-04-03 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inform_for_method', '0004_alter_inform_for_method_service_method'),
        ('second_table', '0003_alter_second_table_inform_for_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='second_table',
            name='inform_for_method',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='inform_for_method.inform_for_method'),
        ),
    ]
