# Generated by Django 4.0.3 on 2024-02-01 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clusters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_well', models.CharField(max_length=120)),
                ('num_pad', models.CharField(max_length=120)),
                ('well_type', models.CharField(blank=True, choices=[('Горизонтальная', 'Horizontal'), ('Вертикальная', 'Vertical'), ('Наклонно-направленная', 'Oblique Directional'), ('Многозабойная', 'Mzs'), ('Многоствольная', 'Mcc'), ('', 'None Value')], max_length=120)),
                ('time_deleted', models.DateTimeField(blank=True, null=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cluster_set', to='clusters.cluster')),
            ],
            options={
                'verbose_name': 'Well',
                'verbose_name_plural': 'Wells',
                'ordering': ['num_well'],
            },
        ),
    ]
