# Generated by Django 4.0.3 on 2024-02-01 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quality_control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Digital_data',
            fields=[
                ('quality_control', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='digital_data_set', serialize=False, to='quality_control.quality_control')),
                ('well_sect', models.CharField(blank=True, max_length=120)),
                ('parametres_sect', models.CharField(blank=True, max_length=120)),
                ('curve_sect', models.CharField(blank=True, max_length=120)),
                ('log_data_sect', models.CharField(blank=True, max_length=120)),
                ('digital_count', models.FloatField(blank=True, null=True)),
                ('data_status', models.CharField(blank=True, max_length=120)),
            ],
        ),
    ]
