# Generated by Django 4.0.3 on 2024-04-01 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='digital_data',
            options={'verbose_name': 'Данные', 'verbose_name_plural': 'Цифровые данные для отчёта'},
        ),
        migrations.RenameField(
            model_name='digital_data',
            old_name='data_status',
            new_name='data_type',
        ),
        migrations.RemoveField(
            model_name='digital_data',
            name='curve_sect',
        ),
        migrations.RemoveField(
            model_name='digital_data',
            name='log_data_sect',
        ),
        migrations.RemoveField(
            model_name='digital_data',
            name='parametres_sect',
        ),
        migrations.RemoveField(
            model_name='digital_data',
            name='well_sect',
        ),
        migrations.AddField(
            model_name='digital_data',
            name='curveLas',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='digital_data',
            name='curveWitsml',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='digital_data',
            name='log_dataLas',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='digital_data',
            name='log_dataWitsml',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='digital_data',
            name='parameteresLas',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='digital_data',
            name='parameteresWitsml',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='digital_data',
            name='wellLas',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='digital_data',
            name='wellWitsml',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterModelTable(
            name='digital_data',
            table='quality_DigitalData',
        ),
    ]
