# Generated by Django 4.0.3 on 2024-04-01 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digital_data', '0002_alter_digital_data_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='digital_data',
            old_name='data_type',
            new_name='type',
        ),
    ]
