# Generated by Django 4.0.3 on 2024-02-01 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('methods', '0001_initial'),
        ('fields', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Petrophysics_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_deleted', models.DateTimeField(blank=True, null=True)),
                ('separation_of_reservoirs', models.FloatField(blank=True, null=True)),
                ('determination_nature_saturation', models.FloatField(blank=True, null=True)),
                ('determination_Kp', models.FloatField(blank=True, null=True)),
                ('determination_Kng', models.FloatField(blank=True, null=True)),
                ('determination_lithotype', models.FloatField(blank=True, null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_petrophysics_set', to='fields.field')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='method_petrophysics_set', to='methods.method')),
            ],
            options={
                'verbose_name': 'Petrophysics_table',
            },
        ),
    ]
